# Generated by Django 6.1 on 2026-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(help_text='Internal length in cm')),
                ('width', models.FloatField(help_text='Internal width in cm')),
                ('height', models.FloatField(help_text='Internal height in cm')),
                ('max_weight', models.FloatField(help_text='Max weight capacity in kg')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('allowed_categories', models.JSONField(default=list, help_text='List of compatible BoxCategory strings')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('length', models.FloatField(help_text='Length in cm')),
                ('width', models.FloatField(help_text='Width in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('category', models.CharField(blank=True, choices=[('STANDARD', 'Standard Goods'), ('FRAGILE', 'Fragile / Glassware'), ('APPAREL', 'Clothing / Soft Goods'), ('HEAVY_DUTY', 'Heavy Machinery / Tools'), ('LIQUID', 'Bottles / Liquids')], max_length=50)),
            ],
        ),
    ]
